
 export const gameResults = [
  {
    id: '1',
    winnerName: 'Wisdom',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Willie',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: '',
    loserObligation: 'Paid',
    date: '2/3/25',
    year: 2025,
    icon: require('@/assets/images/image1.jpg'),
  },
  {
    id: '2',
    winnerName: 'Joel',
    winnerScores: 5,
    winnerRank: 'B',
    winnerPoint: '',
    loserName: 'Dennis',
    loserScores: 0,
    loserRank: 'C',
    loserPoint: '',
    loserObligation: 'Owing',
    date: '2/4/25',
    year: 2025,
    icon: require('@/assets/images/image2.jpg'),
  },
  {
    id: '3',
    winnerName: 'Gloria',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Dennis',
    loserScores: 0,
    loserRank: 'A',
    loserPoint: '',
    loserObligation: 'Paid',
    date: '2/5/25',
    year: 2025,
    icon: require('@/assets/images/image3.jpg'),
  },
  {
    id: '4',
    winnerName: 'Victor',
    winnerScores: 5,
    winnerRank: 'B',
    winnerPoint: '',
    loserName: 'Jerry',
    loserScores: 0,
    loserRank: 'C',
    loserPoint: '',
    loserObligation: 'Owing',
    date: '2/6/25',
    year: 2025,
    icon: require('@/assets/images/userImagePlaceHolder.jpeg'),
  },
  {
    id: '5',
    winnerName: 'Angela',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Dennis',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: '',
    loserObligation: 'Owing',
    date: '2/7/25',
    year: 2025,
    icon: require('@/assets/images/image5.jpg'),
  },
  {
    id: '6',
    winnerName: 'David',
    winnerScores: 5,
    winnerRank: 'C',
    winnerPoint: '',
    loserName: 'Frank',
    loserScores: 0,
    loserRank: 'D',
    loserPoint: '',
    loserObligation: 'Owing',
    date: '2/8/25',
    year: 2025,
    icon: require('@/assets/images/image6.jpg'),
  },
  {
    id: '7',
    winnerName: 'Faith',
    winnerScores: 5,
    winnerRank: 'C',
    winnerPoint: '',
    loserName: 'Kofi',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: '',
    loserObligation: 'Paid',
    date: '2/9/25',
    year: 2025,
    icon: require('@/assets/images/image7.jpg'),
  },
  {
    id: '8',
    winnerName: 'Maxwell',
    winnerScores: 5,
    winnerRank: 'B',
    winnerPoint: '',
    loserName: 'Cynthia',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: '',
    loserObligation: 'Owing',
    date: '2/10/25',
    year: 2025,
    icon: require('@/assets/images/image8.jpg'),
  },
  {
    id: '9',
    winnerName: 'Abigail',
    winnerScores: 5,
    winnerRank: 'C',
    winnerPoint: '',
    loserName: 'Nana',
    loserScores: 0,
    loserRank: 'C',
    loserPoint: '',
    loserObligation: 'Paid',
    date: '2/11/25',
    year: 2025,
    icon: require('@/assets/images/image9.jpg'),
  },
  {
    id: '10',
    winnerName: 'Samuel',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Isaac',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: '',
    loserObligation: 'Owing',
    date: '2/12/25',
    year: 2025,
    icon: require('@/assets/images/image1.jpg'),
  },
  {
    id: '11',
    winnerName: 'Diana',
    winnerScores: 5,
    winnerRank: 'B',
    winnerPoint: '',
    loserName: 'Peace',
    loserScores: 0,
    loserRank: 'C',
    loserPoint: '',
    loserObligation: 'Paid',
    date: '2/13/25',
    year: 2025,
    icon: require('@/assets/images/image2.jpg'),
  },
  {
    id: '12',
    winnerName: 'George',
    winnerScores: 5,
    winnerRank: 'B',
    winnerPoint: '',
    loserName: 'Blessing',
    loserScores: 0,
    loserRank: 'C',
    loserPoint: '',
    loserObligation: 'Owing',
    date: '2/14/24',
    year: 2024,
    icon: require('@/assets/images/image3.jpg'),
  },
  {
    id: '13',
    winnerName: 'Sylvia',
    winnerScores: 5,
    winnerRank: 'C',
    winnerPoint: '',
    loserName: 'Henry',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: '',
    loserObligation: 'Paid',
    date: '2/15/24',
    year: 2024,
    icon: require('@/assets/images/image1.jpg'),
  },
  {
    id: '14',
    winnerName: 'Collins',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Eric',
    loserScores: 0,
    loserRank: 'C',
    loserPoint: '',
    loserObligation: 'Owing',
    date: '2/16/24',
    year: 2024,
    icon: require('@/assets/images/image2.jpg'),
  },
  {
    id: '15',
    winnerName: 'Juliet',
    winnerScores: 5,
    winnerRank: 'C',
    winnerPoint: '',
    loserName: 'Linda',
    loserScores: 0,
    loserRank: 'C',
    loserPoint: '',
    loserObligation: 'Paid',
    date: '2/17/24',
    year: 2024,
    icon: require('@/assets/images/image3.jpg'),
  },
  {
    id: '16',
    winnerName: 'Tony',
    winnerScores: 5,
    winnerRank: 'B',
    winnerPoint: '',
    loserName: 'Steve',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: '',
    loserObligation: 'Owing',
    date: '2/18/23',
    year: 2023,
    icon: require('@/assets/images/image1.jpg'),
  },
  {
    id: '17',
    winnerName: 'Elsie',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Esther',
    loserScores: 0,
    loserRank: 'C',
    loserPoint: 18,
    loserObligation: 'Paid',
    date: '2/19/23',
    year: 2023,
    icon: require('@/assets/images/image2.jpg'),
  },
  {
    id: '18',
    winnerName: 'Fred',
    winnerScores: 5,
    winnerRank: 'C',
    winnerPoint: '',
    loserName: 'Lois',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: 28,
    loserObligation: 'Owing',
    date: '2/20/23',
    year: 2023,
    icon: require('@/assets/images/image3.jpg'),
  },{
    id: '19',
    winnerName: 'Fred',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Benjamin',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: 28,
    loserObligation: 'Owing',
    date: '2/20/23',
    year: 2023,
    icon: require('@/assets/images/image3.jpg'),
  },{
    id: '20',
    winnerName: 'Fred',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'John',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: 28,
    loserObligation: 'Owing',
    date: '2/20/23',
    year: 2023,
    icon: require('@/assets/images/image3.jpg'),
  },{
    id: '21',
    winnerName: 'Fred',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Jude',
    loserScores: 0,
    loserRank: 'B',
    loserPoint: '',
    loserObligation: 'Owing',
    date: '2/20/23',
    year: 2023,
    icon: require('@/assets/images/image3.jpg'),
  },{
    id: '22',
    winnerName: 'Wisdom',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Alizeh',
    loserScores: 0,
    loserRank: 'B',
     loserPoint: '',
    loserObligation: 'Paid',
    date: '2/3/25',
    year: 2025,
    icon: require('@/assets/images/image1.jpg'),
  },{
    id: '22',
    winnerName: 'Wisdom',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Fred',
    loserScores: 0,
    loserRank: 'B',
     loserPoint: '',
    loserObligation: 'Paid',
    date: '2/3/25',
    year: 2025,
    icon: require('@/assets/images/image1.jpg'),
  },{
    id: '22',
    winnerName: 'Wisdom',
    winnerScores: 5,
    winnerRank: 'A',
    winnerPoint: '',
    loserName: 'Fred',
    loserScores: 0,
    loserRank: 'B',
     loserPoint: '',
    loserObligation: 'Paid',
    date: '2/3/27',
    year: 2025,
    icon: require('@/assets/images/image1.jpg'),
  },
  
];